# Generated by Django 3.1.7 on 2021-02-21 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_prep', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('plan', models.TextField()),
                ('travel_start_date', models.DateField()),
                ('travel_end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('planner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_planner', to='travel_prep.user')),
                ('travelers', models.ManyToManyField(related_name='trip_travelers', to='travel_prep.User')),
            ],
        ),
    ]
